// <auto-generated />
namespace MITT_Intern_2019_10_10.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class seewat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seewat));
        
        string IMigrationMetadata.Id
        {
            get { return "201910300252454_seewat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
